# Generated by Django 3.1.7 on 2021-04-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_garbage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Garbage_Entry',
        ),
    ]
